os: 
  - linux
language: java
jdk:
  - oraclejdk8
sudo: false

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
    apt: true
    directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.gradle/nodejs/
    - node_modules

env: 
  - NODE_VERSION=4.4.3
install: 
  - nvm install $NODE_VERSION
  - nvm use $NODE_VERSION
  - npm install -g npm
  - npm install -g gulp
  - npm install -g bower
  - ./gradlew wrapper
  - npm install
before_script: 
  - npm -v
  - java -version
  - gulp -v
  - bower -v
script: 
  - gulp build
  - ./gradlew assemble -x test
  - gulp test
  - ./gradlew check
notifications:
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false

after_script:
  - echo "== CHECKSTYLE_RESULT =="; cat "build/reports/checkstyle/main.xml"; echo "== END_CHECKSTYLE_RESULT =="
  - echo "== PMD_RESULT =="; cat "build/reports/pmd/main.xml"; echo "== END_PMD_RESULT =="
  - echo "== FINDBUGS_RESULT =="; cat "build/reports/findbugs/main.xml"; echo "== END_FINDBUGS_RESULT =="
  - ./gradlew jacocoTestReport coveralls
