version: '2'
services:
    thefirstorder-app:
        image: thefirstorder
        external_links:
            - thefirstorder-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/thefirstorder?useUnicode=true&characterEncoding=utf8&useSSL=false
        ports:
            - 8080:8080
    thefirstorder-mysql:
        extends:
            file: mysql.yml
            service: thefirstorder-mysql
